/**
 * The site icon as DATA: the brand tokens, the letter's outline, the SVG
 * they compose into, and the two binary formats the icon ships in. Pure —
 * no browser, no filesystem — so every piece is unit-testable, and
 * `generate-icons.ts` (which needs Chromium to rasterise) is the only part
 * with side effects.
 *
 * WHY THE LETTER IS A PATH, NOT <text>: browsers render an icon file in an
 * isolated context that loads nothing external, so an SVG asking for
 * `font-family: Poppins` would get whatever sans-serif the OS has. The
 * header's "M" therefore has to be baked in as an outline. The numbers in
 * GLYPH were measured from Poppins ExtraBold itself — rendered at 1000 px on
 * a canvas and scanned row by row (learning log 2026-09-07) — so the icon
 * draws the same letter as the header.
 */

/** Brand tokens. Mirror `--color-honey` / `--color-ink` in src/index.css; icons.test.ts pins them equal. */
export const HONEY = '#f6c244'
export const INK = '#46281c'

/**
 * Poppins ExtraBold "M" as a 13-corner polygon in the glyph's own box: 823
 * wide × 705 tall (its cap height at 1000 units). Clockwise from the
 * top-left corner of the left stem: along the top (each diagonal leaves its
 * stem's top edge 40 units in, at x=236 and x=587, and the two meet at the
 * inner notch, 411.5/452); down the right stem; then back along the bottom:
 * up the right stem's inner edge to where the diagonal peels off it (y=309),
 * down the diagonal's outer edge to the FLAT foot (330..493 — this face cuts
 * the middle of the M flat at the baseline rather than to a point), up the
 * left diagonal's outer edge, and down the left stem's inner edge.
 */
export const GLYPH = {
  width: 823,
  height: 705,
  points: [
    [0, 0], [236, 0], [411.5, 452], [587, 0], [823, 0],
    [823, 705], [627, 705], [627, 309], [493, 705],
    [330, 705], [196, 309], [196, 705], [0, 705],
  ],
} as const

export type IconOptions = {
  /** Side of the square in SVG user units; everything else scales with it. */
  size?: number
  /**
   * Corner radius as a fraction of the side. 0.3 is the design canvas's
   * header mark (12 px on 40). 0 gives a full-bleed square for iOS, which
   * clips its own corner radius and would composite transparent corners
   * over black.
   */
  radius?: number
  /**
   * Cap height of the "M" as a fraction of the side. The header draws the
   * letter at 32% of its square; an icon that is 16 px wide in a tab needs
   * a bigger letter to stay readable, so the icon departs from the canvas
   * here (rule 16, exception 2 — a size the mock never draws).
   */
  capHeight?: number
}

/** The "M" scaled to `capHeight × size` and centred in a `size` box, as SVG path data. */
export function glyphPath(size: number, capHeight: number): string {
  const scale = (size * capHeight) / GLYPH.height
  const dx = (size - GLYPH.width * scale) / 2
  const dy = (size - GLYPH.height * scale) / 2
  const commands = GLYPH.points.map(
    ([x, y], i) => `${i === 0 ? 'M' : 'L'}${fixed(dx + x * scale)} ${fixed(dy + y * scale)}`,
  )
  return `${commands.join(' ')} Z`
}

/** The complete icon: honey rounded square, ink "M". */
export function iconSvg({ size = 64, radius = 0.3, capHeight = 0.6 }: IconOptions = {}): string {
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}">`,
    '  <!-- Generated by scripts/generate-icons.ts from scripts/icons.ts; edit those, not this file. -->',
    `  <rect width="${size}" height="${size}" rx="${fixed(size * radius)}" fill="${HONEY}"/>`,
    `  <path d="${glyphPath(size, capHeight)}" fill="${INK}"/>`,
    '</svg>',
    '',
  ].join('\n')
}

/** Two decimals, no trailing zeros — keeps the path readable and the file small. */
function fixed(n: number): string {
  return String(Math.round(n * 100) / 100)
}

/**
 * Width and height straight from a PNG's header: an 8-byte signature, then
 * the IHDR chunk, whose payload starts with width and height as big-endian
 * uint32 at byte offsets 16 and 20. Big-endian is network byte order — the
 * `ntohl` of C; DataView takes the endianness as an argument on every read
 * instead of a cast that silently trusts the host CPU.
 */
export function pngSize(png: Uint8Array): { width: number; height: number } {
  const view = new DataView(png.buffer, png.byteOffset, png.byteLength)
  const isPng =
    png.byteLength >= 24 && view.getUint32(0) === 0x89504e47 && view.getUint32(12) === 0x49484452
  if (!isPng) throw new Error('not a PNG')
  return { width: view.getUint32(16), height: view.getUint32(20) }
}

/**
 * Packs PNG images into one .ico container — the format Windows 3.1
 * introduced and browsers, Safari and Google's crawler still fetch as
 * /favicon.ico. It is a directory followed by the images:
 *
 *   ICONDIR         6 bytes        reserved=0, type=1 (icon), count
 *   ICONDIRENTRY   16 bytes each   width, height (one byte each; 0 means 256),
 *                                  palette size=0, reserved=0, colour planes=1,
 *                                  bits per pixel=32, image byte length,
 *                                  byte offset of the image from file start
 *   images                         whole PNG files — allowed since Vista,
 *                                  and what every browser reads today
 *
 * Every integer is little-endian. In C++ this is two packed structs and an
 * fwrite each; here DataView.setUint16/32 spell the endianness out per field.
 */
export function encodeIco(images: { size: number; png: Uint8Array }[]): Uint8Array {
  const HEADER = 6
  const ENTRY = 16
  const directoryLength = HEADER + ENTRY * images.length
  const total = directoryLength + images.reduce((sum, image) => sum + image.png.byteLength, 0)
  const out = new Uint8Array(total)
  const view = new DataView(out.buffer)

  view.setUint16(0, 0, true) // reserved
  view.setUint16(2, 1, true) // 1 = icon, 2 = cursor
  view.setUint16(4, images.length, true)

  let offset = directoryLength
  images.forEach(({ size, png }, i) => {
    const { width, height } = pngSize(png)
    if (width !== size || height !== size || size < 1 || size > 256) {
      throw new Error(`ico entry ${i}: declared ${size} px, PNG is ${width}x${height} (max 256)`)
    }
    const entry = HEADER + ENTRY * i
    out[entry] = size === 256 ? 0 : size
    out[entry + 1] = size === 256 ? 0 : size
    out[entry + 2] = 0 // no palette
    out[entry + 3] = 0 // reserved
    view.setUint16(entry + 4, 1, true) // colour planes
    view.setUint16(entry + 6, 32, true) // bits per pixel: RGBA
    view.setUint32(entry + 8, png.byteLength, true)
    view.setUint32(entry + 12, offset, true)
    out.set(png, offset)
    offset += png.byteLength
  })
  return out
}
